-- ============================================================
-- MIGRATION: Multi-Warehouse Support
-- Mô tả: Thêm hỗ trợ nhiều kho con trong một cửa hàng
--        Mỗi kho có capacity (sức chứa) và priority (ưu tiên nhập)
-- Tác giả: Auto-generated by Antigravity
-- Ngày: 2026-03-04
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- 1. Bảng kho_con: Các kho con trong mỗi cửa hàng
-- ============================================================
CREATE TABLE IF NOT EXISTS `kho_con` (
  `MaKho`     INT          NOT NULL AUTO_INCREMENT,
  `MaCH`      INT          NOT NULL COMMENT 'Thuộc cửa hàng nào',
  `TenKho`    VARCHAR(100) NOT NULL COMMENT 'VD: Kho 1, Kho Lạnh',
  `Capacity`  INT          NOT NULL DEFAULT 10000 COMMENT 'Sức chứa tối đa (đơn vị sản phẩm)',
  `Priority`  INT          NOT NULL DEFAULT 1     COMMENT 'Ưu tiên: nhỏ = được chọn trước',
  `ViTri`     VARCHAR(255)     NULL COMMENT 'Mô tả vị trí vật lý trong kho',
  `TinhTrang` TINYINT(1)   NOT NULL DEFAULT 1     COMMENT '1: Hoạt động, 0: Ngưng',
  `GhiChu`    TEXT             NULL,
  `NgayTao`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MaKho`),
  UNIQUE KEY `uq_priority_per_store` (`MaCH`, `Priority`),
  UNIQUE KEY `uq_name_global` (`TenKho`),
  KEY `idx_mach` (`MaCH`),
  KEY `idx_tinhtrang` (`TinhTrang`),
  CONSTRAINT `fk_khoco_cuahang` FOREIGN KEY (`MaCH`) REFERENCES `cua_hang` (`MaCH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Kho con trong mỗi cửa hàng — có capacity và priority';

-- ============================================================
-- 2. Bảng ton_kho_chi_tiet: Tồn kho chi tiết theo kho con
-- ============================================================
CREATE TABLE IF NOT EXISTS `ton_kho_chi_tiet` (
  `MaKho`       INT NOT NULL COMMENT 'Kho con cụ thể',
  `MaSP`        INT NOT NULL,
  `SoLuongTon`  INT NOT NULL DEFAULT 0,
  `CapNhatLuc`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MaKho`, `MaSP`),
  KEY `idx_masp` (`MaSP`),
  CONSTRAINT `fk_tkct_kho`     FOREIGN KEY (`MaKho`) REFERENCES `kho_con`  (`MaKho`),
  CONSTRAINT `fk_tkct_sanpham` FOREIGN KEY (`MaSP`)  REFERENCES `sanpham`  (`MaSP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Tồn kho chi tiết theo từng kho con';

-- ============================================================
-- 3. Bảng chitiet_phanbokho: Log phân bổ khi nhập hàng
-- ============================================================
CREATE TABLE IF NOT EXISTS `chitiet_phanbokho` (
  `MaPhanBo`  INT NOT NULL AUTO_INCREMENT,
  `MaPN`      INT NOT NULL COMMENT 'Phiếu nhập',
  `MaSP`      INT NOT NULL,
  `MaKho`     INT NOT NULL,
  `SoLuong`   INT NOT NULL COMMENT 'Số lượng phân bổ vào kho này',
  `ThoiGian`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MaPhanBo`),
  KEY `idx_mapn`  (`MaPN`),
  KEY `idx_masp`  (`MaSP`),
  KEY `idx_makho` (`MaKho`),
  CONSTRAINT `fk_pb_phieunhap` FOREIGN KEY (`MaPN`)  REFERENCES `phieunhap` (`MaPN`) ON DELETE CASCADE,
  CONSTRAINT `fk_pb_sanpham`   FOREIGN KEY (`MaSP`)  REFERENCES `sanpham`   (`MaSP`),
  CONSTRAINT `fk_pb_kho`       FOREIGN KEY (`MaKho`) REFERENCES `kho_con`   (`MaKho`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Log phân bổ số lượng sản phẩm vào từng kho con khi nhập';

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 4. Data mẫu: Kho con cho 3 cửa hàng hiện có
--    (Chi nhánh Q1=1, Q7=2, Thủ Đức=3)
--    Mỗi cửa hàng có: Kho 1 (priority=1, cap=5000) và Kho 2 (priority=2, cap=3000)
-- ============================================================
INSERT IGNORE INTO `kho_con` (`MaCH`, `TenKho`, `Capacity`, `Priority`, `ViTri`, `GhiChu`) VALUES
  -- Chi nhánh Q1
  (1, 'Kho 1', 5000, 1, 'Tầng trệt, phía sau quầy', 'Kho chính, ưu tiên nhập đầu tiên'),
  (1, 'Kho 2', 3000, 2, 'Tầng 2', 'Kho phụ, nhận hàng khi Kho 1 đầy'),
  -- Chi nhánh Q7
  (2, 'Kho 1', 5000, 1, 'Tầng trệt', 'Kho chính'),
  (2, 'Kho 2', 3000, 2, 'Phía sau',  'Kho phụ'),
  -- Chi nhánh Thủ Đức
  (3, 'Kho 1', 5000, 1, 'Tầng trệt', 'Kho chính'),
  (3, 'Kho 2', 3000, 2, 'Phía sau',  'Kho phụ');

-- ============================================================
-- 5. Migrate dữ liệu tồn kho hiện tại vào ton_kho_chi_tiet
--    Toàn bộ tồn kho cũ → vào "Kho 1" của mỗi cửa hàng
-- ============================================================
INSERT IGNORE INTO `ton_kho_chi_tiet` (`MaKho`, `MaSP`, `SoLuongTon`)
SELECT kc.MaKho, tk.MaSP, tk.SoLuongTon
FROM `ton_kho` tk
JOIN `kho_con` kc ON kc.MaCH = tk.MaCH AND kc.Priority = 1
WHERE tk.SoLuongTon > 0;
